
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    refresh_token TEXT
);



CREATE TABLE IF NOT EXISTS expenses (
   id SERIAL PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   amount NUMERIC NOT NULL,
   category VARCHAR(255) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   user_id INTEGER NOT NULL,
   CONSTRAINT fk_user
           FOREIGN KEY (user_id)
           REFERENCES users(id)
           ON DELETE CASCADE
);